##Создание нового предложения
POST  http://localhost:4000/offers/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV2Z2VuaXlAbWFpbC5ydSIsImlkIjoiNjM2MTg0NTgyMDQ5NjZjMjMzMmFiNTBiIiwiaWF0IjoxNjY3MzM1MjgyLCJleHAiOjE2Njc1MDgwODJ9.VIjSjvSAwi60hXXNvqFAlziYmxzLXAQW-8AlCVtMA5w

{
    "title": "Nice apartment",
    "cityName": "Cologne",
    "city": {
        "name": "Cologne",
        "location": {
            "latitude": 50.938361,
            "longitude": 6.959974
        }
    },
    "isPremium": true,
    "isFavorite": true,
    "description": "hello world",
    "postDate": "2022-09-08T14:30:30.182Z",
    "rating": 5,
    "rooms": 2,
    "guests": 5,
    "price": 1000,
    "comments": 0,
    "amenityes": ["Air"],
    "location": {
        "latitude": 48.843610000000005,
        "longitude": 2.338499
    },
    "userId": "63618458204966c2332ab50b"
}
###

##Редактирование предложения
PATCH http://localhost:4000/offers/6362642401570ae7b2f97e21/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV2Z2VuaXlAbWFpbC5ydSIsImlkIjoiNjM2MTg0NTgyMDQ5NjZjMjMzMmFiNTBiIiwiaWF0IjoxNjY3MzM1MjgyLCJleHAiOjE2Njc1MDgwODJ9.VIjSjvSAwi60hXXNvqFAlziYmxzLXAQW-8AlCVtMA5w

{
    "title": "Nice apartment",
    "images": [

    ],
    "isPremium": false,
    "isFavorite": true,
    "description": "hello world",
    "postDate": "2022-09-08T14:30:30.182Z",
    "rating": 2,
    "rooms": 2,
    "guests": 5,
    "price": 3000,
    "comments": 0,
    "amenityes": ["Air"],
    "previewImage": "http://imagePreview.jpg",
    "location": {
        "latitude": 48.843610000000005,
        "longitude": 2.338499
    },
    "userId": "63618458204966c2332ab50b"
}
###

## Удаление предложения
DELETE  http://localhost:4000/offers/6360f3b49c090776b282fb7c/delete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV2Z2VuaXlAbWFpbC5ydSIsImlkIjoiNjM1ZDgxNjY1NzQ1ZjUxMDQzYTAwYjJhIiwiaWF0IjoxNjY3Mjk4MTk4LCJleHAiOjE2Njc0NzA5OTh9._GwC-j-NhHMMgm7AxYVd2fCjOWJiXtr5PNEuX40QC60
###

## Получение списка предложений по аренде
GET  http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
###

## Получение детальной информации о предложении.
GET  http://localhost:4000/offers/63618489204966c2332ab50e HTTP/1.1
Content-Type: application/json
###

## Получение списка комментариев для предложения.
GET  http://localhost:4000/comments/63613753a09a825dcc3e371c HTTP/1.1

###

## Добавление комментария для предложения.
POST  http://localhost:4000/comments/63618489204966c2332ab50e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV2Z2VuaXlAbWFpbC5ydSIsImlkIjoiNjM2MTM2MTdhMDlhODI1ZGNjM2UzNzBhIiwiaWF0IjoxNjY3MzE1MzY4LCJleHAiOjE2Njc0ODgxNjh9.wQ2HVQxMeExO0hdivpAzHjaeImO4RHyuTwrt6tHyeXc

{
    "commentText": "Hello world!!!",
    "postDate": "2022-11-02T10:45:55.437Z",
    "rating": 5,
    "userId": "63613617a09a825dcc3e370a"
}
###

## Создание нового пользователя.
POST  http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "Evgeniy2",
    "email": "evgeniy2mail.ru",
    "password": "123456",
    "isPro": "true",
    "avatarUrl": "evgeniy.png"
}
###

##  Вход в закрытую часть приложения.
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "evgeniy@mail.ru",
    "password": "123456"
}
###

##  Проверка состояния пользователя.
GET http://localhost:4000/users/auth HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV2Z2VuaXlAbWFpbC5ydSIsImlkIjoiNjM2MTg0NTgyMDQ5NjZjMjMzMmFiNTBiIiwiaWF0IjoxNjY3NDEwOTE1LCJleHAiOjE2Njc1ODM3MTV9.PCkH5oc3cQ_WoWxQHWJxL91X_sa1z-OMEWsUsEpCOmg

###

## Получение премиальных предложений
GET  http://localhost:4000/offers/premium/cologne HTTP/1.1
Content-Type: application/json
###


###

## Получения списка предложений, добавленных в избранное.

GET  http://localhost:4000/offers/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV2Z2VuaXlAbWFpbC5ydSIsImlkIjoiNjM2MTg0NTgyMDQ5NjZjMjMzMmFiNTBiIiwiaWF0IjoxNjY3MzM1MjgyLCJleHAiOjE2Njc1MDgwODJ9.VIjSjvSAwi60hXXNvqFAlziYmxzLXAQW-8AlCVtMA5w

###

## Добавление/удаление предложения в/из избранное.
PATCH   http://localhost:4000/offers/favorites/6362642401570ae7b2f97e21 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV2Z2VuaXlAbWFpbC5ydSIsImlkIjoiNjM2MTg0NTgyMDQ5NjZjMjMzMmFiNTBiIiwiaWF0IjoxNjY3MzM1MjgyLCJleHAiOjE2Njc1MDgwODJ9.VIjSjvSAwi60hXXNvqFAlziYmxzLXAQW-8AlCVtMA5w

{
    "isFavorite": true
}

###

## Отправка аватарки пользователю
POST http://localhost:4000/users/634e92ea7dd68f8986a447bf/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/china/Documents/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
