openapi: '3.0.2'
info:
  title: API сервер для проекта «Шесть городов»
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов»
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0

tags:
- name: offers
  description: Действия с объявлениями
- name: users
  description: Действия с пользователем
- name: comments
  description: Действия с комментариями

paths:
  /offers/:
    get:
      tags:
        - "offers"
      summary: Получение списка предложений.
      description: Получение массива предложений. По умолчанию не более 60 предложений.

      responses:
          "200":
            description: Получен список предложений.

          "500":
            description: Ошибка сервера.

  /offers/:offerId:
    get:
      tags:
        - "offers"
      summary: Получение предложения
      description: Получение предложения по идентификатору.

      responses:
        "200":
          description: Предложение с идентификатором offeId. Объект offer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'

        "404":
          description: Пользователь не найден.

  /offers/create:
    post:
      tags:
        - "offers"
      summary: Создание предложения
      description: Создание нового предложения

      requestBody:
        description: Информация для создания нового предложения.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/offers'
        required: true

      responses:
        "201":
          description: Новое предложение создано. Объект offer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'

        "400":
          description: Неверный формат данных

        "401":
          description: Пользователь неавторизован.

  /offers/:offerId/delete:
    delete:
      tags:
        - "offers"
      summary: Удаление предложения
      description: Удаление предложения по идентификатору.

      responses:
        "204":
          description: Предложение удалено.

        "404":
          description: Предложение не найдено.

  /offers/:offerId/update:
    patch:
      tags:
        - "offers"
      summary: Обновление предложения
      description: Обновление предложения по идентификатору.

      requestBody:
        description: Информация для создания нового предложения.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/offers'
        required: true

      responses:
        "204":
          description: Предложение обновлено. Объект offer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'

        "400":
          description: Неверный формат данных

        "401":
          description: Пользователь неавторизован.

  /offers/premium/:city:
    get:
      tags:
        - "premium"
      summary: Получение премиальных предложений.
      description: Получение 3-х премиальных предложений для города.

      responses:
        "200":
          description: Получен список премиальных предложений.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'

        "404":
          description: Предложения не найдены.

  /offers/favorites:
    get:
      tags:
        - "favorites"
      summary: Получение избранных предложений.
      description: Получения списка предложений, добавленных в избранное.

      responses:
        "200":
          description: Получен список предложений добавленных в избранное
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'
                required: true

        "401":
          description: Пользователь неавторизован, необходимо пройти авторизацию.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorizedError'

  /offers/favorites/:offerId:
    patch:
      tags:
        - "favorites"
      summary: Добавить/Убрать в/из избранное.
      description: Добавление или удаление предложения из избранного.

      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/favorites'
                required: true
                userTokenRequest: 'fdsfdfsfsdf'

      responses:
        "201":
          description: Предложение добавлено/удалено в/из избранное.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'

  /users/login:
    post:
      tags:
        - "users"
      summary: Авторизация пользователя
      description: Авторизация по email и password

      requestBody:
        description: Информация для Авторизация.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/usersLogin'
        required: true

      responses:
        "200":
          description: Пользователь авторизован.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'

        "400":
          description: Неверный формат данных

        "401":
          description: Пользователь не найден.

  /users/register:
    post:
      tags:
        - "users"
      summary: Регистрация пользователя
      description: Регистрация нового пользователя

      requestBody:
        description: Информация для регистрации
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'

      responses:
        "201":
          description: Пользователь зарегистрирован.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'

        "409":
          description: Конфликт. Пользователь существует.

        "400":
          description: Неверный формат данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /users/auth:
    get:
      tags:
        - "users"
      summary: Проверка авторизации
      description: Проверка авторизации пользователя

      requestBody:
        description: Информация для получения сведений об авторизации пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userTokenRequest'

      responses:
        "200":
          description: Пользователь авторизован.

        "401":
          description: Пользователь неавторизован.

        "500":
          description: Серверная ошибка. Не найден заголовок.

  /comments/:offerId:
    get:
      tags:
        - "comments"
      summary: Получение комментариев.
      description: Получение комментариев по предложению.

      responses:
        "200":
          description: Получен список комментариев в виде массива.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comments'
        
        "404":
          description: Предложение с данным идентификатором не найдено.

    post:
      tags:
        - "comments"
      summary: Добавление комментария.
      description: Добавление нового комментария по идентификатору предложения.

      requestBody:
        description: Информация для добавления нового комментария
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/comments'
        required: true

      responses:
        "201":
          description: Комментарий добавлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comments'
        
        "400":
          description: Неверный формат данных

        "404":
          description: Предложение не найдено.

components:
  schemas:
    offers:
      type: object
      properties:
        title:
          type: string
          example: "Penthouse, 4-5 rooms + 5 balconies"

        description:
          type: string
          example: "Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance."

        postDate:
          type: string
          example: "2022-09-08T14:30:30.182Z"

        city: 
          type: object
          example: {
            name: "Cologne",
            location: {
              "latitude": 50.938361,
              "longitude": 6.959974,
            }
          }

        previewImage:
          type: string
          example: "https://10.react.pages.academy/static/hotel/4.jpg"

        images:
          type: array
          example: [
              "https://10.react.pages.academy/static/hotel/17.jpg",
              "https://10.react.pages.academy/static/hotel/9.jpg",
              "https://10.react.pages.academy/static/hotel/10.jpg",
              "https://10.react.pages.academy/static/hotel/14.jpg",
              "https://10.react.pages.academy/static/hotel/6.jpg",
              "https://10.react.pages.academy/static/hotel/5.jpg"
          ]

        isPremium:
          type: boolean
          example: false

        isFavorite:
          type: boolean
          example: false

        rating:
          type: number
          example: 5

        type:
          type: string
          example: "apartment"

        rooms:
          type: number
          example: 3

        guests:
          type: number
          example: 5

        price:
          type: number
          example: 1000

        amenityes:
          type: array
          example: [
            "Dishwasher",
            "Air conditioning",
            "Breakfast",
            "Baby seat",
            "Fridge",
            "Washer",
            "Towels",
            "Coffee machine",
            "Laptop friendly workspace"
          ]

        userId:
          type: string
          example: "634e92ea7dd68f8986a447ca"

        comments:
          type: number
          example: 3

        location:
          type: object
          example: {
            "latitude": 50.934361,
            "longitude": 6.943974,
          }

    users:
      type: object
      properties:
        name:
          type: string
          example: 'Angelina'
        
        email:
          type: string
          example: 'email@gmail.com'
        
        password:
          type: string
          example:

        isPro:
          type: boolean
          example: true
        
        avatarUrl:
          type: string
          example: "https://htmlacademy/avatar.jpg"

    usersLogin:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV2Z2VuaXlAbWFpbC5ydSIsImlkIjoiNjM2MTg0NTgyMDQ5NjZjMjMzMmFiNTBiIiwiaWF0IjoxNjY3MzgwNDkyLCJleHAiOjE2Njc1NTMyOTJ9.7Y_bSq4DW6I_aNbh2urK0reE03R4HF4c4kBnWozgbxU"

        email:
          type: string
          example: "mail@gmail.com"
    
    userTokenRequest:
      type: object
      properties:
        Autorization:
          type: string
          example: "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV2Z2VuaXlAbWFpbC5ydSIsImlkIjoiNjM2MTg0NTgyMDQ5NjZjMjMzMmFiNTBiIiwiaWF0IjoxNjY3MzgwNDkyLCJleHAiOjE2Njc1NTMyOTJ9.7Y_bSq4DW6I_aNbh2urK0reE03R4HF4c4kBnWozgbxU"

    comments:
      type: object
      properties:
        commentText:
          type: string
          example: Hello world

        postDate:
          type: string
          example: ISODate('2022-11-02T10:45:55.437Z')

        rating:
          type: number
          example: 5

        author:
          type: string
          example: "634e92ea7dd68f8986a447ca"

    favorites:
      type: object
      properties:
        isFavorite:
          type: boolean
          example: true
    
    error:
      type: object
      properties:
        errorType:
          type: string
          example: "VALIDATION_ERROR"
        
        error:
          type: string
          example: "Validation error"

        details:
          type: array
          example: [
                {
                    "property": "email",
                    "value": "evgeniy2mail.ru",
                    "messages": ["email must be valid"]
                }]

    unauthorizedError:
      type: object
      properties:
        errorType:
          type: string
          example: "COMMON_ERROR"
        
        error:
          type: string
          example: "Unauthorized"

        details:
          type: array
          example: []